### ISSUE TITLE
CSSでのボタンの大きさやその中の文字の配列大きさが上手く変更できない

### ISSUE THREAD

**Issue by 198711987** [hrt4423/Asoda#59]
<div class="situmon1">　　　　　　　　　　　　　　　　
    <button>
      <p>😊👑 @user</p>
      <p>yyyy/mm/ddに投稿             👍</p>
      <p>タイトル                      100</p>
      <p>📌タグ</p>
      <p>回答件数：ｘｘ</p>
    </button>   　
ここまでhtml
ここからcss
.situmon1{
  position: absolute;
  top: 80px;
  left:250px;
  width: 700px;
  height:150px;
  background-color:#FFF
}
上のようにプログラムを書きましたが背景だけ変更されてボタンの大きさが変わらない事とボタン内の文字の大きさや位置を変更する方法が分かりません。

**Comment by hrt4423** [comment]
css側で指定するタグが違います。
サイズを変えたいのはボタン要素なのでそれを指定する必要があります。

```css
.situmon1 button{
  width: 300px;
  font-size: 10px;
}
```
文字の大きさや位置についても同様です。ユーザ名のPタグに`id="user-name"`を追加したうえで、それを指定しています。
```css
#user-name{
  text-align: start;
  font-size: 30px;
}
```
これでcssが適用されるはずです。
